apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-service
  labels:
    app: products-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: products-service
  template:
    metadata:
      labels:
        app: products-service
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      - name: wait-for-mongodb
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -zv mongodb 27017; do echo waiting for mongodb; sleep 2; done;']
      containers:
      - name: products-service
        image: ecommerce/products-service:latest
        ports:
        - containerPort: 5000
          name: grpc
        - containerPort: 5050
          name: http
        env:
        - name: PORT
          value: "5050"
        - name: GRPC_PORT
          value: "5000"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/products"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:5672"
        envFrom:
        - configMapRef:
            name: products-service-config
        - secretRef:
            name: products-service-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /health
            port: 5050
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
