apiVersion: batch/v1
kind: Job
metadata:
  name: users-db-migrations
  namespace: ecommerce-production
spec:
  template:
    spec:
      containers:
      - name: users-migrations
        image: ecommerce/users-service:1.0.0  # Use specific version tag
        imagePullPolicy: Always
        command: ["npm", "run", "typeorm:run"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "users-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        envFrom:
        - configMapRef:
            name: users-service-config
        - secretRef:
            name: users-service-secrets
      restartPolicy: Never
  backoffLimit: 4
