apiVersion: v1
kind: Service
metadata:
  name: orders-postgres
  labels:
    app: orders-postgres
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: orders-postgres
