apiVersion: v1
kind: Service
metadata:
  name: users-postgres
  labels:
    app: users-postgres
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  ports:
    - port: 5433
      targetPort: 5433
      protocol: TCP
      name: postgres
  selector:
    app: users-postgres
