apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-postgres
  labels:
    app: users-postgres
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  serviceName: users-postgres
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      containers:
      - name: postgres
        image: postgres:15.5-alpine
        ports:
        - containerPort: 5433
          name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: users_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: users-service-secrets
              key: POSTGRES_PASSWORD
        - name: PGPORT
          value: "5433"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        startupProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U postgres -p 5433
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U postgres -p 5433
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - pg_isready -U postgres -p 5433
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
