apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  labels:
    app.kubernetes.io/part-of: ecommerce-platform
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
