apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - migrations/users-migrations-job.yaml
  - migrations/orders-migrations-job.yaml

patches:
  # Set imagePullPolicy to Never for all deployments
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: products-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: orders-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      kind: Deployment
      name: users-service
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never

  # Reduce resource requests for local development
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 25m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Reduce resource requests for databases
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 25m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Reduce StatefulSet resources for local development
  - target:
      kind: StatefulSet
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 25m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Set replicas to 1 for development environment
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: products-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: orders-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: users-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

configMapGenerator:
  - name: api-gateway-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

  - name: products-service-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

  - name: orders-service-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info

  - name: users-service-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
