apiVersion: batch/v1
kind: Job
metadata:
  name: users-db-migrations
  namespace: ecommerce-development
spec:
  template:
    spec:
      containers:
      - name: users-migrations
        image: users-service:latest
        command: ["npm", "run", "typeorm:run"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "users-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "users_db"
      restartPolicy: Never
  backoffLimit: 4
