apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  labels:
    app: users-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
        app.kubernetes.io/part-of: ecommerce-platform
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: users-service
        image: ecommerce/users-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
          name: http
          protocol: TCP
        - containerPort: 5052
          name: grpc
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5002"
        - name: GRPC_PORT
          value: "5052"
        - name: POSTGRES_HOST
          value: "users-postgres"
        - name: POSTGRES_PORT
          value: "5433"
        - name: POSTGRES_DB
          value: "users_db"
        envFrom:
        - configMapRef:
            name: users-service-config
        - secretRef:
            name: users-service-secrets
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
