apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    app: users-service
    app.kubernetes.io/part-of: ecommerce-platform
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
    - port: 5052
      targetPort: 5052
      protocol: TCP
      name: grpc
  selector:
    app: users-service
