apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-staging

bases:
  - ../../base

resources:
  - migrations/users-migrations-job.yaml
  - migrations/orders-migrations-job.yaml
  - secrets/api-gateway-secrets.yaml
  - secrets/products-service-secrets.yaml
  - secrets/orders-service-secrets.yaml
  - secrets/users-service-secrets.yaml
  - ../../base/microservices/api-gateway/hpa.yaml
  - ../../base/microservices/products/hpa.yaml
  - ../../base/microservices/orders/hpa.yaml
  - ../../base/microservices/users/hpa.yaml

patches:
  # Database StatefulSet configurations for staging
  - target:
      kind: StatefulSet
      name: mongodb
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: efs-sc
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi

  - target:
      kind: StatefulSet
      name: users-postgres
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: efs-sc
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi

  - target:
      kind: StatefulSet
      name: orders-postgres
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: efs-sc
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi

  - target:
      kind: StatefulSet
      name: redis
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: efs-sc
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 5Gi

  # Microservices minimal resource configuration for staging
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Minimal HPA configuration for staging
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 90

  # Set imagePullPolicy to Always for all deployments
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  # HPA configurations for staging (minimal scaling)
  - target:
      kind: HorizontalPodAutoscaler
      name: api-gateway-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 90

  - target:
      kind: HorizontalPodAutoscaler
      name: products-service-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 90

  - target:
      kind: HorizontalPodAutoscaler
      name: orders-service-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 90

  - target:
      kind: HorizontalPodAutoscaler
      name: users-service-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
      - op: replace
        path: /spec/metrics/0/resource/target/averageUtilization
        value: 90

images:
  - name: ecommerce/api-gateway
    newName: ${REGISTRY_URL}/ecommerce/api-gateway
    newTag: latest
  - name: ecommerce/products-service
    newName: ${REGISTRY_URL}/ecommerce/products-service
    newTag: latest
  - name: ecommerce/orders-service
    newName: ${REGISTRY_URL}/ecommerce/orders-service
    newTag: latest
  - name: ecommerce/users-service
    newName: ${REGISTRY_URL}/ecommerce/users-service
    newTag: latest

configMapGenerator:
  - name: api-gateway-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true
      - SESSION_STORE=redis
  
  - name: products-service-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true

  - name: orders-service-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true

  - name: users-service-config
    behavior: merge
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true
